version: "3.0"
services: 
  spring-boot-app:
    build: .
    restart: always
    ports:
      - 8000:8080
    depends_on:
      - mysqldb
      
  mysqldb: 
    image: "mysql:5.7"
    restart: always
    volumes: 
      - /sachin/mysqldata:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: userDB
     
      
      
      
    